name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'starter/frontend/**'
      - '.github/workflows/frontend-ci.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'starter/frontend/**'
      - '.github/workflows/frontend-ci.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          cd starter/frontend
          npm ci
          npm run build